name: streamlit-env
channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - scikit-learn
  - numpy
  - pandas
  - joblib
  - xgboost
  - seaborn
  - matplotlib
  - scipy  # If required
  - pip:
      - streamlit