name: streamlit-env
channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy=1.19.5
  - scipy=1.5.4
  - scikit-learn
  - pandas
  - joblib
  - xgboost
  - seaborn
  - matplotlib
  - pip:
      - streamlit