name: streamlit-env
channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy=1.21.6
  - scipy=1.7.3
  - scikit-learn
  - pandas
  - joblib
  - xgboost
  - seaborn
  - matplotlib
  - pip:
      - streamlit